Import('baseEnv')
Import('GetPlatform SetupCppUnit')

import os
pj = os.path.join

sources = Split("""
   runner
   ErrorTest
""")
sources = map(lambda n: n + '.cpp', sources)

env = baseEnv.Copy()
env.Append(CPPPATH = Split('#'),
           LIBPATH = [pj('#', 'build.' + GetPlatform(), 'cppdom')],
           LIBS    = ['cppdom'])
SetupCppUnit(env)

# Win32 doesn't have libdl
if GetPlatform() != 'win32' and GetPlatform() != 'freebsd':
   env.Append(LIBS = Split('dl'))

if GetPlatform() == 'linux':
   env.Append(CXXFLAGS = ['-fexceptions'])

env.Program('runner', sources)
